pull_request_rules:
  - name: Add ready-to-merge label when all reviewers have reviewed
    conditions:
      - "#approved-reviews-by>=2"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      label:
        add:
          - ready-to-merge
  - name: Make bot approve once ready-to-merge label is added
    conditions:
      - label="ready-to-merge"
      - "#approved-reviews-by>=2"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      review:
        type: APPROVE
  - name: Merge after bot approves
    conditions:
      - approved-reviews-by=mergify[bot]
      - "#approved-reviews-by>=3"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - check-success="Ready for merge"
    actions:
      merge:
        method: merge
  - name: Add test label if PR body is checked
    conditions:
      - body~=(?m)^- \[X|x\] Add test-label
    actions:
      label:
        add:
            - test-label
  - name: Comment on PR about test-label
    conditions:
      - label="redirects-needed"
    actions:
      comment:
        message: |
            @{{author}}, since a file was deleted from the `src/pages` and/or `src/fragments` directories, redirects will need to be set up so these previous pages do not 404.
          
            - What is the source address of the redirect? (Where are you trying to redirect from?)

            - What is the target address of the redirect? (Where are you trying to redirect to?)

            - Type of redirect? 301 - permanent redirect or 302 - temporary redirect? (More info on Amplify Hosting redirects here: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html) 
      label:
        remove:
          - "redirects-added"
  - name: Add redirects-needed label if action fails
    conditions:
      - or:
        - check-failure="Check if redirects are needed on PR opened"
        - check-failure="Check if redirects are needed on PR synchronize"
    actions:
      label:
        add:
          - "redirects-needed"