pull_request_rules:
  - name: Add ready-to-merge label when all reviewers have reviewed
    conditions:
      - "#approved-reviews-by>=2"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      label:
        add:
          - ready-to-merge
  - name: Make bot approve once ready-to-merge (do this because we we will make a status check to see if the bot has approved or not)
    conditions:
      - label="ready-to-merge"
    actions:
      review:
        type: APPROVE
  - name: merge when bot approves
    conditions:
      - approved-reviews-by=mergify[bot]
      - "#approved-reviews-by>=3"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
  - name: Add test label if PR body is checked
    conditions:
      - body~=(?m)^- \[X|x\] Add test-label
    actions:
      label:
        add:
            - test-label
  - name: Comment on PR about test-label
    conditions:
      - label="test-label"
    actions:
      comment:
        message: |
            @{{author}}, thank you for requesting to the `test-label`!