name: Check file diff
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  checkIfRedirectsAreNeeded:
    permissions:
      pull-requests: write # used to remove label
      contents: read
    name: Check if redirects are needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
      - name: Get count of deleted files
        run: |
          git fetch origin main
          echo "DELETED_FILES=$(git diff --name-status --diff-filter=D origin/main -- src/team2 ${{ github.pull_request.head.sha }} -- src/team2 | wc -l)" >> $GITHUB_ENV
          echo "Deleted file count: ${{ env.DELETED_FILES }}"
      - name: Add redirects-needed label if there are deleted files
        if: ${{ env.DELETED_FILES > 0 }}
        uses: actions/github-script@v6
        with:
          github-token:  ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            const labels = ['redirects-needed'];
            github.rest.issues.addLabels({ owner, repo, issue_number, labels});
