name: Keep Codeowners Updated Workflow
on:
  pull_request:
    branches: [main]
jobs:
  checkIfCodeownersUpdateNeeded:
    permissions:
      pull-requests: write
    name: Check if CODEOWNERS needs to be updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
      - name: Get count of added files
        run: |
          git fetch origin main
          echo "NEW_FILES<<EOF" >> $GITHUB_ENV
          echo $(git diff --name-only --diff-filter=A origin/main ${{ github.pull_request.head.sha }}) >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Install npm package ignore 
        run: npm install ignore # help verify CODEOWNERS
      - name: Check file against CODEOWNERS
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { NEW_FILES } = process.env
            console.log(NEW_FILES);
            const response = await fetch('https://raw.githubusercontent.com/timngyn-test-org/timngyn/timngyn-patch-2/.github/CODEOWNERS');
            const body = await response.text();
            console.log(body);
            const codeownersFilePatterns = body.split('\n').filter(e => !e.startsWith("#")).filter(e => e.length > 1).map(e => e.split(/\s+/)[0]);
            console.log(codeownersFilePatterns);
            
