name: Check for bot approval
on:
  pull_request_review:
    types: [submitted]
jobs:
  check:
    name: Check for bot approval
    runs-on: ubuntu-latest
    if: github.event.sender != 'mergify[bot]'
    steps:
      - run: exit 1
  block:
    name: Ready for merge
    needs: check
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success! ready to merge"
