name: Check file diff
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  printGithubContext:
    name: Print context
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  checkOnPrOpen:
    name: Check if redirects are needed on PR opened
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
      - name: Get count of deleted files
        run: |
          git fetch origin main
          echo "DELETED_FILES_ON_OPENED=$(git diff --name-status --diff-filter=D origin/main -- src ${{ github.pull_request.head.sha }} -- src | wc -l)" >> $GITHUB_ENV
          echo "Deleted file count: ${{ env.DELETED_FILES_ON_OPENED }}"
      - name: Fail status check if there are deleted files
        if: ${{ env.DELETED_FILES_ON_OPENED > 0 }}
        run: exit 1
  checkOnPRSynchronize:
    name: Check if redirects are needed on PR synchronize
    runs-on: ubuntu-latest
    if: github.event.action == 'synchronize'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
      - name: Get count of deleted files from synchonize
        run: |
          echo "DELETED_FILES_ON_SYNC=$(git diff --name-status --diff-filter=D ${{ github.event.before }}..${{ github.pull_request.head.sha }}  -- src  -- src | wc -l)" >> $GITHUB_ENV
          echo "Deleted file count: ${{ env.DELETED_FILES_ON_SYNC}}
      - name: Fail status check if there are deleted files
        if: ${{ env.DELETED_FILES_ON_SYNC > 0 }}
        run: exit 1